/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


fun main() {
    println("Joaco Ardevol y hoy es 22 de abril de 2025")
    println("Hello Kotlin")
    
    tiposDeDatos()
    calcularAreaRectangulo()

    // Ejemplo de uso de las nuevas funciones
    val numero = 7
    println("El número $numero es: ${esParOImpar(numero)}")
    
    val otroNumero = -5
    println("El número $otroNumero es: ${determinarSigno(otroNumero)}")
}

fun tiposDeDatos() {
    val nombre: String = "Joaco"
    val edad: Int = 16
    val altura: Double = 1.75
    val esEstudiante: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $altura")
    println("Es estudiante: $esEstudiante")
}

fun calcularAreaRectangulo() {
    val base: Double = 5.0
    val altura: Double = 3.0
    val area: Double = base * altura
    
    println("Base: $base")
    println("Altura: $altura")
    println("Área del rectángulo: $area")
}

fun esParOImpar(numero: Int): String {
    return when {
        numero % 2 == 0 -> "Par"
        else -> "Impar"
    }
}

fun determinarSigno(numero: Int): String {
    return when {
        numero > 0 -> "Positivo"
        numero < 0 -> "Negativo"
        else -> "Cero"
    }
}