/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


fun main() {
    println("Joaco Ardevol y hoy es 22 de abril de 2025")
    println("Hello kotline")
    tipos_de_datos()
    calcularAreaRectangulo()
}
fun tipos_de_datos() {
    val nombre: String = "Joaco"
    val edad: Int = 16
    val altura: Double = 1.75
    val esEstudiante: Boolean = true
    
    println("Nombre: $nombre")
    println("Edad: $edad")
    println("Altura: $altura")
    println("Es estudiante: $esEstudiante")
}

fun calcularAreaRectangulo() {
    val base: Double = 5.0
    val altura: Double = 3.0
    val area: Double = base * altura
    
    println("Base: $base")
    println("Altura: $altura")
    println("Área del rectángulo: $area")



}

   
