/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello kotline!"
        }
}

fun main() {
    println("Joaco Ardevol y hoy es 22 de abril de 2025")
    println("Hello kotline")
}
